PezeshkGit/Controllers/DashboardController.cs
using PezeshkGit.Models.Enum;
using System.Web.Mvc;

namespace PezeshkGit.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View(Identity.GetAdminType().ToString());
        }

        public ActionResult Galleries(int? id)
        {
            if (Identity.IsInRole(AdminType.Secretary)) return RedirectToAction("Index", "Dashboard");
            else return View();
        }

        public ActionResult Posts(int? id)
        {
            if (Identity.IsInRole(AdminType.Secretary)) return RedirectToAction("Index", "Dashboard");
            else return View();
        }

        public ActionResult Categories()
        {
            if (Identity.IsInRole(AdminType.Secretary)) return RedirectToAction("Index", "Dashboard");
            else return View();
        }

        public ActionResult Messages(int? id)
        {
            if (Identity.IsInRole(AdminType.BlogManager)) return RedirectToAction("Index", "Dashboard");
            else return View();
        }

        public ActionResult Comments()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            if (Identity.IsInRole(AdminType.BlogManager)) return RedirectToAction("Index", "Dashboard");
            return View();
        }

        public ActionResult Admins()
        {
            if (Identity.IsInRole(AdminType.FullAdmin)) return View();
            return RedirectToAction("Index", "Dashboard");
        }
    }
}

PezeshkGit/Controllers/FAQController.cs
using System.Web.Mvc;

namespace PezeshkGit.Controllers
{
    public class FAQController : Controller
    {
        // GET: FAQ
        public ActionResult Index()
        {
            Api.FAQController con = new Api.FAQController();
            var aa = con.GetFAQs();
            
            return View();
        }
    }
}

PezeshkGit/Controllers/GalleryController.cs
using PezeshkGit.Data;
using PezeshkGit.Models.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace PezeshkGit.Controllers
{
    public class GalleryController : Controller
    {
        #region _context
        readonly ApplicationDbContext _context;
        public GalleryController() => _context = new ApplicationDbContext();
        protected override void Dispose(bool disposing) => _context.Dispose();
        #endregion

        // GET: Gallery
        public ActionResult Index()
        {
            var galleries = _context.Galleries.ToList();
            var categories = _context.Categories.ToList();
            var viewModel = new GalleryListViewModel
            {
                Galleries = galleries,
                Categories = categories
            };
            return View(viewModel);
        }
    }
}

PezeshkGit/Controllers/PostsController.cs
using PezeshkGit.Data;
using PezeshkGit.Models.ViewModels;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace PezeshkGit.Controllers
{
    public class PostsController : Controller
    {
        #region _context
        readonly ApplicationDbContext _context;
        public PostsController() => _context = new ApplicationDbContext();
        protected override void Dispose(bool disposing) => _context.Dispose();
        #endregion

        // GET: Posts
        public ActionResult Index()
        {
            var posts = _context.Posts.ToList().FindAll(m => m.Published == true);
            var categories = _context.Categories.ToList();
            var viewModel = new PostListViewModel
            {
                Posts = posts,
                Categories = categories
            };
            return View(viewModel);
        }

        public ActionResult View(int? id)
        {
            string aa = "a" + id;
            if (id == null) throw new HttpException(404, "");
            var model = _context.Posts.Include(c => c.Comments).SingleOrDefault(c => c.ID == id);
            return View(model);
        }
    }
}

PezeshkGit/Views/Shared/_Dashboard.cshtml
@using PezeshkGit.Models.Enum;
<html>
<head>
    <meta name="robots" content="noindex">
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/DashboardCSS")
    @Scripts.Render("~/bundles/lib")
    @Scripts.Render("~/bundles/Regex")
</head>
<body>
    @{
        AdminType accType = Identity.GetAdminType();
    }
    <div class="mypanel">
        <div class="right hideMenu">
            @Html.ActionLink("سایت", "Index", "Home", null, new { @class = "home_button" })

            <section>
                @Html.ActionLink("داشبورد", "Index", "Dashboard", null, new { @class = "dashboard" })

                @if (accType == AdminType.FullAdmin)
                {
                    @Html.ActionLink("گالری", "Galleries", "Dashboard", null, new { @class = "gallery" })
                    @Html.ActionLink("مقالات", "Posts", "Dashboard", null, new { @class = "blog" })
                    @Html.ActionLink("دسته بندی ها", "Categories", "Dashboard", null, new { @class = "categories" })
                    @Html.ActionLink("پیام ها", "Messages", "Dashboard", null, new { @class = "chat" })
                    @Html.ActionLink("نظرات", "Comments", "Dashboard", null, new { @class = "comnt" })
                    @Html.ActionLink("سوالات متداول", "FAQ", "Dashboard", null, new { @class = "faq" })
                    @Html.ActionLink("مدیران", "Admins", "Dashboard", null, new { @class = "admins" })
                }

                else if (accType == AdminType.BlogManager)
                {
                    @Html.ActionLink("گالری", "Galleries", "Dashboard", null, new { @class = "gallery" })
                    @Html.ActionLink("مقالات", "Posts", "Dashboard", null, new { @class = "blog" })
                    @Html.ActionLink("نظرات", "Comments", "Dashboard", null, new { @class = "comnt" })
                    @Html.ActionLink("دسته بندی ها", "Categories", null, "Dashboard", new { @class = "categories" })
                }

                else if (accType == AdminType.Secretary)
                {
                    @Html.ActionLink("پیام ها", "Messages", "Dashboard", null, new { @class = "chat" })
                    @Html.ActionLink("نظرات", "Comments", "Dashboard", null, new { @class = "comnt" })
                    @Html.ActionLink("سوالات متداول", "FAQ", "Dashboard", null, new { @class = "faq" })
                }
            </section>

            <form action="/Account/Logout" id="logoutForm" method="post">
                @Html.AntiForgeryToken()
                <a class="exit_button" href="javascript:document.getElementById('logoutForm').submit()">خروج</a>
            </form>
        </div>

        <div class="left">
            <div class="header" id="left_header">
                <div class="menu_res" onclick="ResMenuControl(true)"></div>
                <div class="menu_res_close" onclick="ResMenuControl()"></div>
                @if (accType != AdminType.BlogManager)
                {
                    <script>
                        $.ajax({
                            url: "/Api/Message/GetUnreadMessagesCount",
                            method: "GET",
                            success: (res) => {
                                if (res != 0) {
                                    let chat = $("<a>").addClass("chat").attr("href", "Dashboard/Messages").appendTo("#left_header.header");
                                    let cc = $("<span>").addClass("chat_count").appendTo(chat);
                                    if (res > 99) cc.html("99+");
                                    else cc.html(res);
                                }
                            }
                        });
                    </script>
                }
            </div>
            @RenderBody()
        </div>
    </div>

    <script>
        $(".left").scroll(() => {
            let obj = $(".left > .header > a.chat, .newButton")

            if ($(".left").scrollTop() > 40) obj.css("display", "none")
            else obj.css("display", "block")
        });
        $(".mypanel > .right").scroll(() => {
            let obj = $(".menu_res_close")

            if ($(".mypanel > .right").scrollTop() > 0) obj.css("display", "none")
            else obj.css("display", "block")
        });

        function ResMenuControl(mode) {
            if (mode) {
                $('.menu_res_close').css('display', 'block');
                $('.menu_res').css('display', 'none');
            }
            else {
                $('.menu_res_close').css('display', 'none');
                $('.menu_res').css('display', 'block');
            }
            $('.mypanel > .right').toggleClass('hideMenu')
        }

        var actName = '@ViewContext.RouteData.Values["action"]';

        if (actName == "Index") $(".dashboard").addClass("sel");
        else if (actName == "Galleries") $(".gallery").addClass("sel");
        else if (actName == "Posts") $(".blog").addClass("sel");
        else if (actName == "Categories") $(".categories").addClass("sel");
        else if (actName == "Comments") $(".comnt").addClass("sel");
        else if (actName == "Messages") $(".chat").addClass("sel");
        else if (actName == "FAQ") $(".faq").addClass("sel");
        else if (actName == "Admins") $(".admins").addClass("sel");
    </script>
</body>
</html>

PezeshkGit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/lib")
    @Styles.Render("~/Content/jplist")
    @Scripts.Render("~/bundles/jplist")
    @{
        var CurrentUrl = Request.Url.AbsolutePath.ToLower();
    }
    @if (CurrentUrl.Contains("/posts/view/"))
    {
        @RenderSection("metas");
    }
</head>
<body>
    @if (Identity.IsAuthenticated())
    {
        <div class="auth_ok">
            <span>خوش آمدید</span>
            @Html.ActionLink("ورود به پنل کاربری", "Index", "Dashboard")
        </div>
    }

    <div id="header">
        <div class="holder">
            <ul class="menu">
                <li>@Html.ActionLink("صفحه اصلی", "Index", "Home")</li>
                <li>@Html.ActionLink("گالری تصاویر", "Index", "Gallery")</li>
                <li>@Html.ActionLink("مقالات", "Index", "Posts")</li>
                @if (CurrentUrl == "/home/index" || CurrentUrl == "/")
                {
                    <li><a onclick="GoToReserve()">نوبت دهی</a></li>
                }
                else
                {
                    <li>@Html.ActionLink("نوبت دهی", "Index", "Home", new { @goto = "reserve" }, null)</li>
                }
                <li>@Html.ActionLink("پرسش و پاسخ", "Index", "FAQ")</li>
            </ul>
        </div>
    </div>

    <div class="responsive_menu_open" onclick="resToggle(true)"></div>
    <div class="responsive_menu">
        <div class="responsive_menu_close" onclick="resToggle(false)"></div>
        <ul class="menu_items">
            <li>@Html.ActionLink("صفحه اصلی", "Index", "Home")</li>
            <li>@Html.ActionLink("گالری تصاویر", "Index", "Gallery")</li>
            <li>@Html.ActionLink("مقالات", "Index", "Posts")</li>
            @if (CurrentUrl == "/home/index" || CurrentUrl == "/")
            {
                <li><a onclick="GoToReserve()">نوبت دهی</a></li>
            }
            else
            {
                <li>@Html.ActionLink("نوبت دهی", "Index", "Home", new { @goto = "reserve" }, null)</li>
            }
            <li>@Html.ActionLink("پرسش و پاسخ", "Index", "FAQ")</li>
        </ul>
    </div>

    <div id="content">
        @if (!CurrentUrl.Contains("manage") && !CurrentUrl.Contains("about") && !CurrentUrl.Contains("account"))
        {
            <div class="about_section">
                <div class="right">
                    <img src="~/Content/Images/first.png" />
                </div>
                <div class="left">
                    <div class="first">
                        <span>درباره دکتر</span>
                        <h2>دکتر عسگری عباس زاده</h2>
                    </div>
                    <span>فوق تخصص جراحی پلاستیک، ترمیمی و زیبایی</span>
                    <ul>
                        <li>عضو رسمی جامعه جراحان ایران</li>
                        <li>گذراندن دوره تکمیلی لیزر در دبی</li>
                    </ul>
                    <a href="~/Home/About">
                        خواندن اطلاعات بیشتر
                        <div class="flesh_box">
                            <span class="line"></span>
                        </div>
                    </a>
                </div>
            </div>
        }

        @RenderBody()
    </div>

    <div id="footer" class="footer">
        <ul class="menu mfooter">
            <li>@Html.ActionLink("صفحه اصلی", "Index", "Home")</li>
            <li>@Html.ActionLink("گالری تصاویر", "Index", "Gallery")</li>
            <li>@Html.ActionLink("مقالات", "Index", "Posts")</li>
            @if (CurrentUrl == "/home/index" || CurrentUrl == "/")
            {
                <li><a onclick="GoToReserve()">نوبت دهی</a></li>
            }
            else
            {
                <li>@Html.ActionLink("نوبت دهی", "Index", "Home", new { @goto = "reserve" }, null)</li>
            }
            <li>@Html.ActionLink("پرسش و پاسخ", "Index", "FAQ")</li>
        </ul>
    </div>

    <script>
        function resToggle(open) {
            if (open) {
                $('.responsive_menu').css('animation', 'resOpenAnim 0.5s forwards');
                $('.responsive_menu_open').animate({ opacity: '0' }, "0.3");
            }
            else {
                $('.responsive_menu').css('animation', 'resCloseAnim 0.5s forwards');
                $('.responsive_menu_open').animate({ opacity: '1' }, "0.3");
            }
        }

        if (new URLSearchParams(window.location.search).get("goto") == "reserve") GoToReserve();

        function GoToReserve() {
            $([document.documentElement, document.body]).animate({
                scrollTop: $('#reserveBox').offset().top
            }, 1500);
        }

        let anc = ".menu > li:nth-child(";
        let path = "@CurrentUrl";

        if (path == "/") $(anc + "1) > a").addClass("sel");
        else if (path == "/gallery") $(anc + "2) > a").addClass("sel");
        else if (path == "/posts" || path.includes("/posts/view")) $(anc + "3) > a").addClass("sel");
        else if (path == "/faq") $(anc + "5) > a").addClass("sel");
    </script>
</body>
</html>